name: nginx_le_container
version: 8.2.1
documentation: https://nginxle.noojee.dev/
description: Commands that live in the nginx-le docker container.
repository: https://github.com/bsutton/nginx-le
environment: 
  sdk: '>=2.16.1 <3.0.0'
dependencies: 
  args: ^2.0.0
  async: ^2.4.2
  cron: ^0.4.0
  dcli: ^1.17.5
  http: ^0.13.0
  intl: ^0.17.0
  isolates: ^3.0.0
  meta: ^1.0.0
  nginx_le_shared: ^8.0.4
  path: ^1.6.4
  public_suffix: ^3.0.0
  scope: ^2.2.1
  uuid: ^3.0.1
  xml: ^5.0.2
dev_dependencies: 
  lint_hard: ^1.0.0
  mocktail: ^0.3.0
  settings_yaml: ^3.0.1
  test: ^1.0.0
dependency_overrides: 
  nginx_le_shared: 
    path: ../shared
