name: nginx_le
version: 9.0.1
homepage: https://github.com/bsutton/nginx-le
documentation: https://nginxle.onepub.dev/
description: Nginx-LE provides a docker container and tools to create an Nginx web server that automatically acquires and renews HTTPS certificates.
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  args: ^2.0.0
  async: ^2.4.2
  cron: ^0.5.0
  dcli: ^3.0.0
  docker2: ^4.0.0
  encrypt: ^5.0.0
  http: ^0.13.0
  intl: ^0.18.0
  isolates: ^3.0.0
  meta: ^1.0.0
  nginx_le_shared: ^9.0.1
y
  path: ^1.6.4
  pub_release: ^9.0.0
  pub_semver: ^2.0.0
  public_suffix: ^3.0.0
  settings_yaml: ^7.0.0
  uuid: ^3.0.0
  validators2: ^5.0.0
  xml: ^6.1.0
  yaml: ^3.0.0
dev_dependencies: 
  lint_hard: ^4.0.0
  test: ^1.0.0
executables: 
  nginx-le: nginx-le
