name: nginx_le_shared
version: 8.3.6
homepage: https://github.com/bsutton/nginx-le
documentation: https://nginxle.noojee.dev/
description: shared library used by Nginx-LE
environment: 
  sdk: '>=2.16.1 <3.0.0'
dependencies: 
  args: ^2.3.1
  async: ^2.9.0
  cron: ^0.5.0
  dcli: ^1.36.0
  docker2: ^2.2.8
  http: ^0.13.0
  instant: ^0.4.1
  intl: ^0.17.0
  isolates: ^3.0.0
  mailer: ^5.2.0
  meta: ^1.8.0
  path: ^1.8.2
  public_suffix: ^3.0.0
  scope: ^3.0.0
  settings_yaml: ^4.0.0
  uuid: ^3.0.6
  xml: ^6.1.0
  yaml: ^3.1.1
dev_dependencies: 
  lint_hard: ^2.0.0
  test: ^1.21.4
