name: nginx_le_shared
version: 8.2.2
homepage: https://github.com/bsutton/nginx-le
documentation: https://nginxle.noojee.dev/
description: shared library used by Nginx-LE
environment: 
  sdk: '>=2.16.1 <3.0.0'
dependencies: 
  args: ^2.0.0
  async: ^2.4.2
  cron: ^0.4.0
  dcli: ^1.17.5
  docker2: ^2.2.0
  http: ^0.13.0
  instant: ^0.4.1
  intl: ^0.17.0
  isolates: ^3.0.0
  mailer: ^5.0.0
  meta: ^1.0.0
  path: ^1.6.4
  public_suffix: ^3.0.0
  scope: ^2.2.1
  settings_yaml: ^3.0.1
  uuid: ^3.0.1
  xml: ^5.0.2
  yaml: ^3.1.0
dev_dependencies: 
  lint_hard: ^1.0.0
  test: ^1.0.0
